window.mimiRedFlagBehaviorPairs = {
  guy: [
    ["Mattress on the floor", "Fresh clean sheets"],
    ["Uses ex's Netflix", "Pays his own bills"],
    ["\"U up?\" at 2 AM", "Replies the same day"],
    ["Lives on energy drinks", "Drinks actual water"],
    ["Calls every ex crazy", "Speaks respectfully"],
    ["37 unfinished side hustles", "Finishes what he starts"],
    ["One towel for everything", "Owns multiple towels"],
    ["Owns a sigma course", "Has real hobbies"],
    ["Daily gym mirror selfies", "Asks about your day"],
    ["\"Emotionally unavailable\"", "Communicates clearly"],
    ["Borrows money, forgets", "Pays people back"],
    ["Started 12 podcasts", "Keeps commitments"],
    ["Brags about no sleep", "Takes care of himself"],
    ["Microwaves frozen pizza", "Can cook a meal"],
    ["Ghosts for 3 days", "Says when he's busy"],
    ["Road rage in parking lots", "Stays calm under pressure"],
    ["Never returns shopping carts", "Returns shopping carts"],
    ["Calls waiters \"buddy\" aggressively", "Treats everyone well"],
    ["Has three decorative katanas", "Owns a vacuum cleaner"],
    ["Always on 2% battery", "Charges before leaving"],
    ["Never reads instructions", "Builds furniture correctly"],
    ["Owns crypto, rents a chair", "Owns a chair"],
    ["Car sounds like boss fight", "Uses turn signals"],
    ["Thinks deodorant is optional", "Smells nice"],
    ["Five fantasy leagues, misses birthdays", "Remembers little things"],
    ["Follows 8,000 influencers", "Follows through on plans"],
    ["\"Trust me, bro\"", "Admits when he's wrong"],
    ["Christmas lights in July", "Changes smoke alarm batteries"],
    ["Calls himself alpha", "Confident without labels"],
    ["\"Could've gone pro\"", "Enjoys life as is"],
    ["Argues with customer service", "Kind to service workers"],
    ["Proudly doesn't read books", "Loves learning"],
    ["Asks for gas money", "Plans thoughtful dates"],
    ["Owns 14 gaming headsets", "Owns matching bedsheets"],
    ["\"Women are complicated\"", "Actually listens"],
    ["Entrepreneur in bio only", "Has a steady job"],
    ["Phone always face down", "Nothing to hide"],
    ["Flirts with every cashier", "Makes you feel special"],
    ["Never deletes old food", "Cleans the fridge"],
    ["Peak male podcast addict", "Thinks for himself"],
  ],
  girl: [
    ["\"Live, Laugh, Love\" wall decal", "Has actual hobbies"],
    ["Owns 14 water bottles", "Drinks from one"],
    ["Says \"he's just a friend\"", "Sets clear boundaries"],
    ["Buys plants, forgets plants", "Keeps plants alive"],
    ["Makes TikToks in public", "Feels no need to perform"],
    ["Has 37 skincare products", "Uses the ones she owns"],
    ["Sends \"k.\"", "Uses complete sentences"],
    ["Starts a fight in a dream", "Separates dreams from reality"],
    ["Keeps emergency exes", "Keeps healthy boundaries"],
    ["Three-hour photo shoot", "Enjoys the actual trip"],
    ["Orders salad, eats your fries", "Orders her own fries"],
    ["Says \"I'm literally crazy\"", "Emotionally stable"],
    ["Owns a ring light", "Owns a bookshelf"],
    ["Has 9 tote bags", "Uses a tote bag"],
    ["Makes friends hate her boyfriend", "Keeps her own opinions"],
    ["Posts cryptic sad quotes", "Talks about problems directly"],
    ["\"Do whatever you want\"", "Says what she wants"],
    ["Astrology before accountability", "Takes responsibility"],
    ["Needs 84 photos of brunch", "Eats brunch while warm"],
    ["Buys crystals for everything", "Solves problems normally"],
    ["Has an emotional support Stanley Cup", "Drinks water from a cup"],
    ["Says \"all my exes were toxic\"", "Learns from relationships"],
    ["Flirts for free desserts", "Pays for dessert"],
    ["Turns every outing into content", "Lives in the moment"],
    ["Screenshots every conversation", "Respects privacy"],
    ["Tests your loyalty weekly", "Trusts until proven otherwise"],
    ["Online shops when sad", "Has a savings account"],
    ["Treats Sephora like therapy", "Has healthier coping skills"],
    ["Calls herself a princess", "Treats others like royalty too"],
    ["Checks your location hourly", "Has her own life"],
    ["Uses baby voice on adults", "Speaks like an adult"],
    ["Creates fake scenarios", "Asks direct questions"],
    ["Makes waiters retake photos", "Says thank you"],
    ["Thinks red flags are projects", "Walks away when needed"],
    ["Owns six identical beige sweaters", "Has a personality"],
    ["Makes her dog an Instagram manager", "Just loves her dog"],
    ["Says \"girl math\" for everything", "Knows where money went"],
    ["Needs a committee to choose dinner", "Makes a decision"],
    ["Keeps gifts from every situationship", "Declutters regularly"],
    ["Sends 47 voice notes", "Gets to the point"],
  ],
};
